# Generated by Django 4.1 on 2022-09-03 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spells',
            new_name='Spell',
        ),
    ]
