# Generated by Django 4.1 on 2022-09-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0006_alter_member_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='house',
            field=models.CharField(choices=[('Gryffindor', 'Gryffindor'), ('Ravenclaw', 'Ravenclaw'), ('Hufflepuff', 'Hufflepuff'), ('Slytherin', 'Slytherin')], default='Choose your houses', max_length=20),
        ),
    ]
