# Generated by Django 4.1 on 2022-09-11 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0008_alter_member_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='members',
        ),
    ]
