# Generated by Django 4.1 on 2022-09-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0009_remove_spell_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
    ]
