# Generated by Django 4.1 on 2022-09-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('picture', models.TextField()),
                ('house', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Spells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('use', models.CharField(max_length=50)),
                ('effect', models.TextField()),
            ],
        ),
    ]
