# Generated by Django 4.1 on 2022-09-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0003_spell_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to='da.member'),
        ),
    ]
